version: '3.4'

services:
  ledfxdev4:
    image: ledfxdev4
    build:
      context: .
      dockerfile: ./Dockerfile-4stage
    entrypoint: ledfx --host 0.0.0.0 -p 8888
    hostname: ledfx
    restart: unless-stopped
    ports:
      - 8888:8888